{
 "title": "Smartmeter",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Power Consumption History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(smartmeter_consumption_wh_total{}[2m]) * 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Consumption",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smartmeter_power_w{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(\n    increase(smartmeter_consumption_wh_total{}[1d])[$__range:1d]\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}